version: "1.3"
services:
  # Dev

  # Dev 환경을 위한 Commerce API의 MySQL 데이터베이스
  commerce-project-api-dev-db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # Dev 환경을 위한 Authorization 서버의 MySQL 데이터베이스
  commerce-project-authorization-server-dev-db:
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # Dev 환경을 위한 Query 서버의 MySQL 데이터베이스
  commerce-project-query-dev-db:
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci



  # Dev 환경의 Kafka UI 설정 (Kafka 클러스터 모니터링 도구)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest # Kafka UI 이미지
    ports:
      - "9999:8080"  # Kafka UI 포트 매핑
    environment:
      KAFKA_CLUSTERS_0_NAME: local-environment # 클러스터 이름
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092 # 부트스트랩 서버 정보
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 # Zookeeper 연결 정보

  # Dev 환경의 Redis 설정 (인메모리 데이터 저장소)
  query-redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # ----------------------------------------------------------
  # TEST

  # Test 환경을 위한 Commerce API의 MySQL 데이터베이스
  commerce-project-api-test-db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # 테스트 환경의 Redis 설정
  query-redis-test:
    image: redis:latest
    ports:
      - "6380:6379"
