version: "1"
services:
  commerce-project-api-dev-db:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  commerce-project-api-test-db:
    image: mysql:8.0.32
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  commerce-project-authorization-server-dev-db:
    image: mysql:8.0.32
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  commerce-project-query-dev-db:
    image: mysql:8.0.32
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - 9001:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev

