spring:
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis
commerce:
  messaging:
    base-package:
      cache-config: com.albert.commerce.adapter.out.persistence
logging:
  level:
    org.springframework.data.redis: DEBUG


