spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-secret: secret
            client-name: oidc-client
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/oidc-client
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: openid,profile
        provider:
          oidc-client:
            issuer-uri: http://localhost:9000
            user-name-attribute: sub
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client:
            RestTemplate: DEBUG



